Add a way for advertisers advertise on Guppy
guppyco/fishbowl pull request #119
Opened 2021-12-23 09:16 UTC by autn

Hi @YPCrumble, this PR is used for adding a way for advertisers to advertise on Guppy.
Please help me to review and change my Github role so I can add the secrets or help me to add the Stripe testing API keys to the secrets. Thanks!

2021-12-23 20:47 UTC, YPCrumble approved these changes
@autn the way we add secrets is to add them to the vault in our deployments repo so that they get added as environment variables to the site. Remember that the vault file should be encrypted. Truong or Ngoc should be able to show you :D.

2021-12-24 07:40 UTC, autn commented
@YPCrumble I see, but what I want in this case is to pass the Github actions :D

2021-12-31 20:09 UTC, YPCrumble approved these changes

2022-01-07 14:35 UTC, YPCrumble requested changes
@autn looking good! Just a couple comments.

2022-01-07 14:35 UTC, YPCrumble commented on advertisers/models.py
> +    monthly_budget = models.IntegerField(blank=False, null=False)
@autn for now let's make the monthly budget linked to an advertisement, not the advertiser.

2022-01-07 14:35 UTC, YPCrumble commented on advertisers/templates/advertisers/signup.html
> +  <h4 class="col-md-8 offset-md-2">Sign up advertiser</h4>
@autn let's change this to "Create your first ad on Guppy."

2022-01-10 08:47 UTC, merged